version: 0.2

env:
  variables:
    REPO_URI: "788364686470.dkr.ecr.ap-southeast-1.amazonaws.com/fbvn-hoanl"
    AWS_DEFAULT_REGION: "ap-southeast-1"
phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPO_URI
  build:
    commands:
      - echo Build Docker image...
      - docker build -t $REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION $REPO_URI:latest
  post_build:
    commands:
      - echo Push to ECR...
      - docker push $REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $REPO_URI:latest
      - printf '[{"name":"fbvn-hoanl-dk","imageUri":"%s"}]' $REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
